# https://aka.ms/yaml

variables:
  DotNetVersion: 5.0.100-rc.2.20459.1

jobs:
- job: mac
  pool:
    vmImage: macOS-latest
  variables:
    LogDirectory: $(Build.ArtifactStagingDirectory)/logs
  steps:
    - bash: >
        curl -L https://dot.net/v1/dotnet-install.sh > dotnet-install.sh &&
        sh dotnet-install.sh --version $(DotNetVersion) --install-dir ~/.dotnet/ --verbose &&
        dotnet --list-sdks
      displayName: install .NET $(DotNetVersion)

    - bash: |
        set -x
        ls -la /Applications
        DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcrun clang -v
        sudo xcode-select -s /Applications/Xcode.app
        cat /Users/runner/Library/Preferences/Xamarin/Settings.plist
        /usr/libexec/PlistBuddy -c "set :AppleSdkRoot /Applications/Xcode.app" ~/Library/Preferences/Xamarin/Settings.plist
        cat /Users/runner/Library/Preferences/Xamarin/Settings.plist
        xcode-select -p
        xcrun xcode-select -p
        xcodebuild -checkFirstLaunchStatus
        xcrun xcodebuild -checkFirstLaunchStatus
        clang -v
        xcrun clang -v
        DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer xcrun clang -v
        install_name_tool --help
        exit 0
      displayName: diagnostics

    - bash: |
        dotnet build net6-samples.sln -c Debug -bl:$(LogDirectory)/Debug.binlog
      displayName: build samples

    - task: CopyFiles@2
      displayName: copy artifacts
      inputs:
        contents: |
          *Android/**/*-Signed.apk
          *iOS/**/*.app/**
        targetFolder: $(Build.ArtifactStagingDirectory)
        overWrite: true
      condition: always()

    - task: PublishPipelineArtifact@1
      displayName: publish artifacts
      inputs:
        artifactName: mac-artifacts
        targetPath: $(Build.ArtifactStagingDirectory)
      condition: always()
